# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {2}  -id {Board 49-26}  -suppress 
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/imt/vhdl-imt/carrefour/carrefour.cache/wt [current_project]
set_property parent.project_path D:/imt/vhdl-imt/carrefour/carrefour.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/mux.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/deco.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/counter_sec.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/counter_1s.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/control.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/operative.vhd
  D:/imt/vhdl-imt/carrefour/carrefour.srcs/sources_1/new/top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7k70tfbv676-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
